### ISSUE TITLE
Unable to establish SSL connections

### ISSUE THREAD

**Issue by bkr32** [offensive-security/Kali-WSL-chroot#4]
Hi, so recently my installation started acting a little strange, it would refuse to apt update or do git pull's

```Ign:1 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Err:2 http://http.kali.org/kali kali-rolling InRelease
  Connection failed [IP: 192.99.200.113 80]
Err:3 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch Release
  Could not handshake: Error in the push function. [IP: 13.80.10.205 443]
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.```

```fatal: unable to access 'https://github.com///': gnutls_handshake() failed: Error in the push function.```

**Comment by offensive-security** [comment]
Looks like you might have a number of things wrong. First off, the repo you reference with issues with SSL is not a Kali repo. The Kali repo you list is standard HTTP. So this is a general networking issue across multiple repos here. Plus, we don't recommend putting in additional repos on Kali. 

Does not look like this is a Kali bug, but rather your install is broken. I would suggest reinitializing your WSL instance. Also if you want to use https on repos, read https://www.kali.org/news/kali-linux-repository-https-support/.

**Comment by bkr32** [comment]
hi, i have reset my setup entirely but still encounter the following error 
```Err:1 http://http.kali.org/kali kali-rolling InRelease
  Connection failed [IP: 192.99.200.113 80]```
i have also tried with https, both show up on a browser when i visit them
